title: Greg Lomax # your name (or website title) here
logo: "/images/greglomax.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Business Transformation with Data Science
  <br><br>
  Utilizing Python and SQL 
  <br><br>
  <a href="https://www.linkedin.com/in/greglomax/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
